### ISSUE TITLE
Auto detect app even if the app folder tree is not standard

### ISSUE THREAD

**Issue by tdejoigny-ledger** [LedgerHQ/ledger-vscode-extension#12]
For example the Near app is not automatically detected by the extension (makefile is not in the root folder)

**Comment by agrojean-ledger** [comment]
Following merge of https://github.com/LedgerHQ/ledger-vscode-extension/pull/21 Near app is now properly detected and build/test tasks are working properly. 

The latest improvements should cover most tree structures. Closing the issue.
