### ISSUE TITLE
Memorize target device when VS Code is quit

### ISSUE THREAD

**Issue by blucet-ledger** [LedgerHQ/ledger-vscode-extension#39]
Whenever I start VS Code, I have to remember to select the appropriate target since it always falls back to Nano S.
Would it be possible to persist this information and remember the last target used?
Thank you for the great extension!

**Comment by cedelavergne-ledger** [comment]
We already have an available setting: `Default Device`.
Would it be sufficient?

**Comment by cedelavergne-ledger** [comment]
Fixed in v0.7.0
