### ISSUE TITLE
Add "rule enforcer"

### ISSUE THREAD

**Issue by agrojean-ledger** [LedgerHQ/ledger-vscode-extension#6]
Add a feature that would run checks similar to the [CI reusable workflow](https://github.com/LedgerHQ/ledger-app-workflows/blob/master/.github/workflows/reusable_guidelines_enforcer.yml
) that is now mandatory in app repos.

The idea is to check the code of the **apps opened in vscode** like the rule enforcer does in the CI of app repositories.

It is **not** about checking the code of the extension itself.

**Comment by tdejoigny-ledger** [comment]
- check manifest
- check icons
- check app load params --> check db
- check makefile (standard)
- check readme
- check clang

script already present in the docker file ?

**Comment by cedelavergne-ledger** [comment]
Fixed in #55
