### ISSUE TITLE
Issue when using Speculos for Nano S+: wrong binary path

### ISSUE THREAD

**Issue by yogh333** [LedgerHQ/ledger-vscode-extension#7]
When building for Nano S+, binaries are generated in `build/nanos2/bin` but Speculos tries to load the ELF binary from `build/nanosp/bin` thus generating a `file not found error`

One possible fix would be to get the binaries from `bin` folder in the project root folder.

**Comment by tdejoigny-ledger** [comment]
@agrojean-ledger check if this issue has already been fixed
